#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias zshrc='lvim ~/.config/zsh/'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get fastest mirrors
alias mirror="doas reflector -c China,Singapore -l 10 -p http,https --sort rate --verbose --save /etc/pacman.d/mirrorlist && doas pacman -Syy"
alias mirrord="doas reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="doas reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="doas reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias remarkable_ssh='ssh root@10.11.99.1'
alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
# alias cp="cp -i"
# alias mv='mv -i'
# alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="doas pacman-key --init && doas pacman-key --populate archlinux && doas pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"


# vim and emacs
alias vi="lvim"
alias vim="lvim"

# root privileges
alias suvi="doas lvim"
alias sucp="doas cp"
alias sumv="doas mv"
alias surm="doas rm"

# Changing "ls" to "exa"
alias l='exa -F --icons --color=always --group-directories-first'
alias ls='exa -Fal --icons --color=always --group-directories-first' # my preferred listing
alias la='exa -Fa --icons --color=always --group-directories-first'  # all files and dirs
alias ll='exa -Fl --icons --color=always --group-directories-first'  # long format
alias lt='exa -FaT -L 3 --icons --color=always --group-directories-first' # tree listing
alias l.='exa -Fa --icons | egrep "^\."'

# pacman and yay
alias pac='doas pacman'
alias pacsyu='doas pacman -Syu'                  # update only standard pkgs
alias pacsyyu='doas pacman -Syyu'                # Refresh pkglist & update standard pkgs
alias yaysua='yay -Sua --noconfirm'              # update only AUR pkgs (yay)
alias yaysyu='yay -Syu --noconfirm'              # update standard pkgs and AUR pkgs (yay)
alias unlock='doas rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='doas pacman -Rns (pacman -Qtdq)'  # remove orphaned packages

# git
alias addup='git add -u'
alias addall='git add .'
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias commit='git commit -m'
alias fetch='git fetch'
alias pull='git pull origin'
alias push='git push origin'
alias stat='git status'  # 'status' is protected name so using 'stat' instead
alias tag='git tag'
alias newtag='git tag -a'

alias bat1='echo 1 | doas tee -a /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'
alias bat0='echo 0 | doas tee -a /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'
